version: '3.8'

services:
  # MySQL Database
  database:
    image: mysql:8.0
    container_name: sistema_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sistema_treinamentos
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend/migrations:/docker-entrypoint-initdb.d
    networks:
      - sistema-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # Backend API
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: sistema_backend
    environment:
      NODE_ENV: production
      DB_HOST: database
      DB_PORT: 3306
      DB_USER: admin
      DB_PASSWORD: admin123
      DB_NAME: sistema_treinamentos
      SECRET_JWT: seu_jwt_secret_aqui
      FRONTEND_URL: http://localhost:3000
    ports:
      - "3000:3000"
    depends_on:
      database:
        condition: service_healthy
    networks:
      - sistema-network
    volumes:
      - ./backend:/app
      - /app/node_modules

  # Frontend React
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: sistema_frontend
    environment:
      VITE_API_URL: http://localhost:3000
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - sistema-network
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  mysql_data:

networks:
  sistema-network:
    driver: bridge